name: Examples CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive' # Check out the main repo and its submodules

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install top-level dependencies
        # Assuming the top-level Makefile handles bootstrapping
        run: make -C ../.. bootstrap # Run bootstrap from the root

      - name: Check sentiment_api example
        run: |
          cd sentiment_api
          # Placeholder: Add commands to build/test the example
          # Example: make proto2prod-check
          echo "Checking sentiment_api..."

      - name: Check image_processor example
        run: |
          cd ../image_processor
          # Placeholder: Add commands to build/test the example
          echo "Checking image_processor..."
